### ISSUE TITLE
视频文件播放视频

### ISSUE THREAD

**Issue by newbieandroid** [rawchen/AliPan#1]
我自己网盘里面的视频在播放的时候出现403  但是我看你演示网站的视频文件又能成功播放 
![image](https://user-images.githubusercontent.com/25599357/151144667-24fee716-fd68-4735-811b-6a1e04cd6929.png)

**Comment by rawchen** [comment]
你试试用PotPlayer或者其它媒体查看器查看下这个MP4的视频是否为H.264编码，如果你不熟悉视频容器技术的话可以搜索相关知识，mp4只是个视频容器，重要的是视频具体使用的编码格式。因为普通web浏览器支持的媒体编码有限制。
如果是视频文件编码问题解决方案：格式工厂转换
其它问题：q我，博客点关于->QQ

**Comment by newbieandroid** [comment]
> 你试试用PotPlayer或者其它媒体查看器查看下这个MP4的视频是否为H.264编码，如果你不熟悉视频容器技术的话可以搜索相关知识，mp4只是个视频容器，重要的是视频具体使用的编码格式。因为普通web浏览器支持的媒体编码有限制。 如果是视频文件编码问题解决方案：格式工厂转换 其它问题：q我，博客点关于->QQ

通过网页端拿到的refreshToken,在进行/file/get_download_url请求后拿到的直链地址进行请求下载或者播放的时候需要添加阿里的Referer，否则会出现403
